name: Build APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle.properties'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # API 35 + naj
